package com.cs.audit;

/**
 * @author Hadi Movaghar
 */
public enum UserActivityType {
    LOGIN,
    FAILED_LOGIN,

    LOGOUT,

    REFUND_DEPOSIT,
    CANCEL_DEPOSIT,

    CONFIRM_WITHDRAW,
    DECLINE_WITHDRAW,
    CONFIRM_LARGE_WITHDRAW,

    CREATE_USER,
    UPDATE_ANOTHER_USER,

    UPDATE,

    UNBLOCK_PLAYER,
    BLOCK_PLAYER,

    MONTHLY_SUMMARY_REPORT,
    MONTHLY_BONUS_TURNOVER_REPORT,
    MONEY_LAUNDERING_REPORT,

    UPDATE_PLAYER_LIMITATIONS,

    CREATE_BONUS,
    CREATE_PROMOTION,
    UPDATE_BONUS,
    ADD_ADJUSTABLE_BONUS_MONEY,
    CANCEL_PLAYER_BONUS,
    GRANT_MANUAL_BONUS,
    GRANT_MANUAL_BONUS_FAILED,

    GIVE_PROMOTION_TO_PLAYER,
    UPDATE_PROMOTION,
    GIVE_BONUS_TO_PLAYER,

    UPDATE_PLAYER_WALLET,
    UPDATE_PLAYER_BONUS,
    CREATE_ADJUSTABLE_BONUS,
    STORE_BANK_ACCOUNT_INFO,

    ADD_PLAYER_TO_WHITELIST,
    REMOVE_PLAYER_TO_WHITELIST,
    ADD_IP_ADDRESS_TO_WHITELIST,
    REMOVE_IP_ADDRESS_FROM_WHITELIST,

    CREATED_TERMS_AND_CONDITIONS_VERSION,
    ACTIVATED_TERMS_AND_CONDITIONS_VERSION,

    PATCH_CALL
}
